build:
  test:
    image: abakpress/dind-testing
    pull: true
    privileged: true
    volumes:
      - /home/data/drone/images:/images
      - /home/data/drone/gems:/bundle
      - /home/data/drone/key_cache:/ssh_keys
    environment:
      - RUBY_IMAGE_TAG=2.2-latest
      - DOCKER_RUBY_VERSION=2.2
      - COMPOSE_FILE_EXT=drone
    commands:
      - wrapdocker docker -v

      - fetch-images
        --image whilp/ssh-agent
        --image abakpress/ruby-app:$RUBY_IMAGE_TAG

      - dip ssh add -T -v /ssh_keys -k /ssh_keys/id_rsa
      - dip provision
      - dip rspec

  release:
    image: abakpress/gem-publication:latest
    pull: true
    when:
      event: push
    commands:
      - release-gem
